# Generated by kpex 0.3.10
crashbackups stop
drc off
gds read /foss/designs/unicasss-tools/frac-n-pll-vco-unic_cass/gds/blocks/PHASE_FREQ_DET.gds
load PHASE_FREQ_DET
select top cell
flatten PHASE_FREQ_DET_flat
load PHASE_FREQ_DET_flat
cellname delete PHASE_FREQ_DET -noprompt
cellname rename PHASE_FREQ_DET_flat PHASE_FREQ_DET
select top cell
extract path /foss/designs/unicasss-tools/frac-n-pll-vco-unic_cass/pex/PHASE_FREQ_DET__PHASE_FREQ_DET/magic_RC
extract all
ext2sim labels on
ext2sim -p /foss/designs/unicasss-tools/frac-n-pll-vco-unic_cass/pex/PHASE_FREQ_DET__PHASE_FREQ_DET/magic_RC
extresist tolerance 1
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/unicasss-tools/frac-n-pll-vco-unic_cass/pex/PHASE_FREQ_DET__PHASE_FREQ_DET/magic_RC -o /foss/designs/unicasss-tools/frac-n-pll-vco-unic_cass/pex/PHASE_FREQ_DET__PHASE_FREQ_DET/magic_RC/PHASE_FREQ_DET.pex.spice
quit -noprompt
