# Generated by kpex 0.3.8
crashbackups stop
drc off
gds read /foss/designs/frac-n-pll-vco-unic_cass/layout/CP.gds
load CP
select top cell
flatten CP_flat
load CP_flat
cellname delete CP -noprompt
cellname rename CP_flat CP
select top cell
extract path /foss/designs/frac-n-pll-vco-unic_cass/pex/CP__CP/magic_RC
extract all
ext2sim labels on
ext2sim -p /foss/designs/frac-n-pll-vco-unic_cass/pex/CP__CP/magic_RC
extresist tolerance 1
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/frac-n-pll-vco-unic_cass/pex/CP__CP/magic_RC -o /foss/designs/frac-n-pll-vco-unic_cass/pex/CP__CP/magic_RC/CP.pex.spice
quit -noprompt
