# Generated by kpex 0.3.10
crashbackups stop
drc off
gds read /foss/designs/unicasss-tools/frac-n-pll-vco-unic_cass/gds/blocks/CHARGE_PUMP_V1.gds
load CHARGE_PUMP
select top cell
flatten CHARGE_PUMP_flat
load CHARGE_PUMP_flat
cellname delete CHARGE_PUMP -noprompt
cellname rename CHARGE_PUMP_flat CHARGE_PUMP
select top cell
extract path /foss/designs/unicasss-tools/frac-n-pll-vco-unic_cass/pex/CHARGE_PUMP_V1__CHARGE_PUMP/magic_RC
extract all
ext2sim labels on
ext2sim -p /foss/designs/unicasss-tools/frac-n-pll-vco-unic_cass/pex/CHARGE_PUMP_V1__CHARGE_PUMP/magic_RC
extresist tolerance 1
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/unicasss-tools/frac-n-pll-vco-unic_cass/pex/CHARGE_PUMP_V1__CHARGE_PUMP/magic_RC -o /foss/designs/unicasss-tools/frac-n-pll-vco-unic_cass/pex/CHARGE_PUMP_V1__CHARGE_PUMP/magic_RC/CHARGE_PUMP.pex.spice
quit -noprompt
