# Generated by kpex 0.3.15
crashbackups stop
drc off
gds read ../../../gds/blocks/BANDGAP_REF.gds
load BANDGAP_REF
select top cell
flatten BANDGAP_REF_flat
load BANDGAP_REF_flat
cellname delete BANDGAP_REF -noprompt
cellname rename BANDGAP_REF_flat BANDGAP_REF
select top cell
extract path .
extract all
ext2sim labels on
ext2sim -p .
extresist tolerance 1.0
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p . -o BANDGAP_REF.pex.spice
quit -noprompt
