# Generated by kpex 0.3.10
crashbackups stop
drc off
gds read /foss/designs/unicasss-tools/frac-n-pll-vco-unic_cass/gds/blocks/BANDGAP_REF.gds
load BANDGAP_REF
select top cell
flatten BANDGAP_REF_flat
load BANDGAP_REF_flat
cellname delete BANDGAP_REF -noprompt
cellname rename BANDGAP_REF_flat BANDGAP_REF
select top cell
extract path /foss/designs/unicasss-tools/frac-n-pll-vco-unic_cass/pex/BANDGAP_REF__BANDGAP_REF/magic_RC
extract all
ext2sim labels on
ext2sim -p /foss/designs/unicasss-tools/frac-n-pll-vco-unic_cass/pex/BANDGAP_REF__BANDGAP_REF/magic_RC
extresist tolerance 1
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/unicasss-tools/frac-n-pll-vco-unic_cass/pex/BANDGAP_REF__BANDGAP_REF/magic_RC -o /foss/designs/unicasss-tools/frac-n-pll-vco-unic_cass/pex/BANDGAP_REF__BANDGAP_REF/magic_RC/BANDGAP_REF.pex.spice
quit -noprompt
