# Generated by kpex 0.3.15
crashbackups stop
drc off
gds read /foss/designs/unicasss-tools/SG13G2_2.4GHz_LC_VCO_FPLL/gds/blocks/LC_VCO_NOIND.gds
load LC_VCO_NOIND
select top cell
flatten LC_VCO_NOIND_flat
load LC_VCO_NOIND_flat
cellname delete LC_VCO_NOIND -noprompt
cellname rename LC_VCO_NOIND_flat LC_VCO_NOIND
select top cell
extract path /tmp/kpex_vco/LC_VCO_NOIND__LC_VCO_NOIND/magic_RC
extract all
ext2sim labels on
ext2sim -p /tmp/kpex_vco/LC_VCO_NOIND__LC_VCO_NOIND/magic_RC
extresist tolerance 1.0
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /tmp/kpex_vco/LC_VCO_NOIND__LC_VCO_NOIND/magic_RC -o /tmp/kpex_vco/LC_VCO_NOIND__LC_VCO_NOIND/magic_RC/LC_VCO_NOIND.pex.spice
quit -noprompt
