# Generated by kpex 0.3.15
crashbackups stop
drc off
gds read ../../../gds/blocks/CHARGE_PUMP_V2.gds
load CHARGE_PUMP
select top cell
flatten CHARGE_PUMP_flat
load CHARGE_PUMP_flat
cellname delete CHARGE_PUMP -noprompt
cellname rename CHARGE_PUMP_flat CHARGE_PUMP
select top cell
extract path .
extract all
ext2sim labels on
ext2sim -p .
extresist tolerance 1.0
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p . -o CHARGE_PUMP.pex.spice
quit -noprompt
