# Generated by kpex 0.3.10
crashbackups stop
drc off
gds read /foss/designs/unicasss-tools/frac-n-pll-vco-unic_cass/gds/blocks/LOOP_FILTER.gds
load LOOP_FILTER
select top cell
flatten LOOP_FILTER_flat
load LOOP_FILTER_flat
cellname delete LOOP_FILTER -noprompt
cellname rename LOOP_FILTER_flat LOOP_FILTER
select top cell
extract path /foss/designs/unicasss-tools/frac-n-pll-vco-unic_cass/pex/LOOP_FILTER__LOOP_FILTER/magic_RC
extract all
ext2sim labels on
ext2sim -p /foss/designs/unicasss-tools/frac-n-pll-vco-unic_cass/pex/LOOP_FILTER__LOOP_FILTER/magic_RC
extresist tolerance 1
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/unicasss-tools/frac-n-pll-vco-unic_cass/pex/LOOP_FILTER__LOOP_FILTER/magic_RC -o /foss/designs/unicasss-tools/frac-n-pll-vco-unic_cass/pex/LOOP_FILTER__LOOP_FILTER/magic_RC/LOOP_FILTER.pex.spice
quit -noprompt
