# Generated by kpex 0.3.10
crashbackups stop
drc off
gds read /foss/designs/unicasss-tools/frac-n-pll-vco-unic_cass/gds/blocks/DSM_N_FREQ_DIV.gds
load DSM_N_FREQ_DIV
select top cell
flatten DSM_N_FREQ_DIV_flat
load DSM_N_FREQ_DIV_flat
cellname delete DSM_N_FREQ_DIV -noprompt
cellname rename DSM_N_FREQ_DIV_flat DSM_N_FREQ_DIV
select top cell
extract path /foss/designs/unicasss-tools/frac-n-pll-vco-unic_cass/pex/DSM_N_FREQ_DIV__DSM_N_FREQ_DIV/magic_RC
extract all
ext2sim labels on
ext2sim -p /foss/designs/unicasss-tools/frac-n-pll-vco-unic_cass/pex/DSM_N_FREQ_DIV__DSM_N_FREQ_DIV/magic_RC
extresist tolerance 1
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/unicasss-tools/frac-n-pll-vco-unic_cass/pex/DSM_N_FREQ_DIV__DSM_N_FREQ_DIV/magic_RC -o /foss/designs/unicasss-tools/frac-n-pll-vco-unic_cass/pex/DSM_N_FREQ_DIV__DSM_N_FREQ_DIV/magic_RC/DSM_N_FREQ_DIV.pex.spice
quit -noprompt
