"""Turn fitted S-parameters into an ngspice ``.subckt`` usable from Xschem.

Realisation
-----------
Each port senses its incident wave and is driven by the reflected wave:

    u_i = V_i + Z0*I_i          (= 2*sqrt(Z0)*a_i)
    y_i = sum_j S_ij(s) * u_j   (= 2*sqrt(Z0)*b_i)
    V_i = y_i + Z0*I_i          realised by R0 in series with a VCVS

Each pole of the shared set becomes a first-order state node driven by u_j:

    real pole  p = -a        x = u/(s+a)
    pair       p = -a +/- jb  x1 = (s+a)/D * u,  x2 = -b/D * u,
                              D = (s+a)^2 + b^2

which matches the partial-fraction basis used by ``vectorfit`` exactly, so the
residues drop straight in as transconductances.

Only R, C, E, G, F and V elements are emitted, so the result loads in ngspice
without extra options and is a drop-in replacement for the HFSS-exported model.
"""
from __future__ import annotations

import numpy as np

from vectorfit import _pair_mask

__all__ = ["write_subckt"]

CSTATE = 1e-12          # state-node capacitance; only the R/C ratio matters


def _fmt(x):
    return f"{x:.12g}"


def write_subckt(path, name, poles, R, D, z0=50.0, header=None):
    """Write the fitted 2-port as a SPICE subcircuit.

    poles : (n,) complex, conjugate pairs adjacent (vectorfit convention)
    R     : (2, 2, n) real residues in the vectorfit basis
    D     : (2, 2) real constant term
    """
    n_ports = R.shape[0]
    if n_ports != 2:
        raise ValueError("this writer emits 2-port models")
    mask = _pair_mask(poles)
    L = []
    w = L.append

    w(f"* {name} - EM-extracted {n_ports}-port model")
    w("* Generated by em/scripts/spice_model.py - do not edit by hand.")
    if header:
        for line in str(header).splitlines():
            w(f"* {line}")
    w(f"* poles={len(poles)}  Z0={z0} ohm")
    w("*")
    w(f".subckt {name} 1 2")
    w("")

    w("* ---- ports: ammeter, reference resistor, reflected-wave source ----")
    for i in (1, 2):
        w(f"Vam{i} {i} n{i} dc 0")
        w(f"R0_{i} n{i} e{i} {_fmt(z0)}")
        w(f"E{i} e{i} 0 y{i} 0 1")
    w("")

    w("* ---- incident wave  u_i = V_i + Z0*I_i ----")
    for i in (1, 2):
        w(f"Ru{i} u{i} 0 1")
        w(f"Gu{i} 0 u{i} {i} 0 1")
        w(f"Fu{i} 0 u{i} Vam{i} {_fmt(z0)}")
    w("")

    w("* ---- reflected-wave accumulators (1 ohm: V = sum of currents) ----")
    for i in (1, 2):
        w(f"Ry{i} y{i} 0 1")
    w("")

    w("* ---- pole states, one bank per driving port ----")
    for j in (1, 2):
        w(f"* driven by u{j}")
        k = 0
        while k < len(poles):
            a = -poles[k].real
            if a <= 0:
                raise ValueError("unstable pole in fit")
            if mask[k] == 0:
                x = f"x{j}_{k}"
                w(f"Cs{j}_{k} {x} 0 {_fmt(CSTATE)}")
                w(f"Rs{j}_{k} {x} 0 {_fmt(1.0 / (a * CSTATE))}")
                w(f"Gs{j}_{k} 0 {x} u{j} 0 {_fmt(CSTATE)}")
                k += 1
            else:
                b = abs(poles[k].imag)
                x1, x2 = f"x{j}_{k}", f"x{j}_{k + 1}"
                w(f"Cs{j}_{k} {x1} 0 {_fmt(CSTATE)}")
                w(f"Rs{j}_{k} {x1} 0 {_fmt(1.0 / (a * CSTATE))}")
                w(f"Gs{j}_{k} 0 {x1} u{j} 0 {_fmt(CSTATE)}")
                w(f"Gx{j}_{k} 0 {x1} {x2} 0 {_fmt(b * CSTATE)}")
                w(f"Cs{j}_{k + 1} {x2} 0 {_fmt(CSTATE)}")
                w(f"Rs{j}_{k + 1} {x2} 0 {_fmt(1.0 / (a * CSTATE))}")
                w(f"Gx{j}_{k + 1} 0 {x2} {x1} 0 {_fmt(-b * CSTATE)}")
                k += 2
        w("")

    w("* ---- residues: y_i = sum_jk gain * x_jk  +  D_ij * u_j ----")
    for i in (1, 2):
        for j in (1, 2):
            for k in range(len(poles)):
                g = R[i - 1, j - 1, k] * (1.0 if mask[k] == 0 else 2.0)
                if g != 0.0:
                    w(f"Gy{i}_{j}_{k} 0 y{i} x{j}_{k} 0 {_fmt(g)}")
            if D[i - 1, j - 1] != 0.0:
                w(f"Gd{i}_{j} 0 y{i} u{j} 0 {_fmt(D[i - 1, j - 1])}")
    w("")
    w(".ends")
    w("")

    with open(path, "w") as fh:
        fh.write("\n".join(L))
    return path
